/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import javax.swing.JOptionPane;
import modelo.*;
/**
 *
 * @author carlos
 */
public class frmAgregarProducto extends javax.swing.JFrame {
    //mis variables
    private String _estado;//estado (Agregar, modificar)
    private int [] _inds;//indices de los datos a editar
    //mis funciones
    //setear el estado del formulario
    public void setEstado(String _estado){
        this._estado=_estado;
    }            
    //rellenar todo el formulario
    public void rellenar(Producto prod,int []_inds){        
        this.txtCodigo.setText(prod.getIdProducto());
        this.txtNombre.setText(prod.getNombre());        
        this.txtCantidad.setText(prod.getCantidad()+"");
        this.txtPC.setText(prod.getPrecioCosto()+"");
        this.txtPV.setText(prod.getPrecioVenta()+"");
        this._inds=_inds;
    }
    public void vaciar(){                
        this.txtCodigo.setText("PROD"+(Producto.getId()+1));
        this.txtNombre.setText("");        
        this.txtCantidad.setText("");
        this.txtDistribuidor.setText("");
        this.txtPC.setText("");
        this.txtPV.setText("");
    
    }
    
    public frmAgregarProducto() {
        initComponents();
        this.setLocationRelativeTo(null);
    }        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panProducto = new javax.swing.JPanel();
        lblCaracteristicasProducto = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblIdDistribuidor = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtDistribuidor = new javax.swing.JTextField();
        lblDetalleProducto = new javax.swing.JLabel();
        lblPC = new javax.swing.JLabel();
        lblPV = new javax.swing.JLabel();
        txtPC = new javax.swing.JTextField();
        txtPV = new javax.swing.JTextField();
        pnImagen = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnVaciar = new javax.swing.JButton();

        setTitle("Agregar Producto");
        setPreferredSize(new java.awt.Dimension(600, 365));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCaracteristicasProducto.setText("Características del Producto");

        lblCodigo.setText("Código:");

        lblNombre.setText("Nombre:");

        lblCantidad.setText("Cantidad:");

        lblIdDistribuidor.setText("Id-Distribuidor:");

        txtCodigo.setEnabled(false);

        lblDetalleProducto.setText("Detalles de Precios");

        lblPC.setText("Precio Compra:");

        lblPV.setText("Precio Venta:");

        pnImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnImagenLayout = new javax.swing.GroupLayout(pnImagen);
        pnImagen.setLayout(pnImagenLayout);
        pnImagenLayout.setHorizontalGroup(
            pnImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        pnImagenLayout.setVerticalGroup(
            pnImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panProductoLayout = new javax.swing.GroupLayout(panProducto);
        panProducto.setLayout(panProductoLayout);
        panProductoLayout.setHorizontalGroup(
            panProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panProductoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panProductoLayout.createSequentialGroup()
                        .addGroup(panProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDetalleProducto)
                            .addGroup(panProductoLayout.createSequentialGroup()
                                .addComponent(lblPC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPC, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPV, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panProductoLayout.createSequentialGroup()
                        .addGroup(panProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCaracteristicasProducto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panProductoLayout.createSequentialGroup()
                                .addGroup(panProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panProductoLayout.createSequentialGroup()
                                        .addComponent(lblIdDistribuidor)
                                        .addGap(32, 32, 32))
                                    .addGroup(panProductoLayout.createSequentialGroup()
                                        .addGroup(panProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCodigo)
                                            .addComponent(lblNombre)
                                            .addComponent(lblCantidad))
                                        .addGap(55, 55, 55)))
                                .addGroup(panProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDistribuidor, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(pnImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        panProductoLayout.setVerticalGroup(
            panProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panProductoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblCaracteristicasProducto)
                .addGroup(panProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panProductoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigo)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(panProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantidad)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdDistribuidor)
                            .addComponent(txtDistribuidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panProductoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(pnImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(lblDetalleProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPC)
                    .addComponent(lblPV)
                    .addComponent(txtPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(panProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 315, 270, 50));

        btnVaciar.setText("Vaciar");
        btnVaciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVaciarMouseClicked(evt);
            }
        });
        getContentPane().add(btnVaciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVaciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVaciarMouseClicked
           this.vaciar();
    }//GEN-LAST:event_btnVaciarMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        try{   
            Util.chequear(new String[]{ this.txtCodigo.getText(), //datos a evaluar
                                        this.txtNombre.getText(),
                                        this.txtCantidad.getText(),
                                        this.txtPC.getText(),
                                        this.txtPV.getText()},
                          new int[][]{{3,5}} //indices de restricciones
                            );
            
            switch(this._estado){
                  case "Agregar"://agregar un producto nuevo                      
                      Producto nProducto=new Producto(this.txtNombre.getText(),Integer.parseInt(this.txtCantidad.getText()),Double.parseDouble(this.txtPC.getText()),Double.parseDouble(this.txtPV.getText()));
                      Market.addProducto(nProducto);
                      frmListaProductos.addRow(nProducto.toVector());                      
                  break;
                  case "Modificar"://modificar datos de productos ya existentes
                      Producto eProducto=Market.getProductos().get(this._inds[0]);
                      eProducto.setNombre(this.txtNombre.getText());
                      eProducto.setCantidad(Integer.parseInt(this.txtCantidad.getText()));
                      eProducto.setPrecioCosto(Double.parseDouble(this.txtPC.getText()));
                      eProducto.setPrecioVenta(Double.parseDouble(this.txtPV.getText()));
                      frmListaProductos.editRow(this._inds[1],new String []{this.txtCodigo.getText(),this.txtNombre.getText(),this.txtPC.getText(),this.txtPV.getText()});
                  break;
            }            
            this.hide();
            
        }catch(Exception err){
            //mensaje de error
            JOptionPane.showMessageDialog(null, err);
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAgregarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVaciar;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCaracteristicasProducto;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDetalleProducto;
    private javax.swing.JLabel lblIdDistribuidor;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPC;
    private javax.swing.JLabel lblPV;
    private javax.swing.JPanel panProducto;
    private javax.swing.JPanel pnImagen;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDistribuidor;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPC;
    private javax.swing.JTextField txtPV;
    // End of variables declaration//GEN-END:variables
}
