/*Formulario Principal SOLARIS */
package vista;

/**
 *
 * @author carlos
 */
import modelo.*;
import java.util.*;
import java.util.Timer;
import javax.swing.JOptionPane;


public class frmSolaris extends javax.swing.JFrame {
    //----------mis variables---------------    
    public static ArrayList<javax.swing.JFrame> frms=new ArrayList(); //todos los formularios que se podrian abrir en el sistema
    private static boolean _ingresar=false;

    //----------mis funciones---------------
    private void init(){
        //Obtener datos de la base de datos
            //usuarios                                                
            Dao.init("Solaris");//inicializar la conexión con la base de datos
            
            ArrayList<ArrayList<String>> A;            
                        // columnas  /  tabla(s)  / condición / llaves foráneas para crear condición
            A=Dao.select("User,Password", "Usuario",null);
                Market.createUsuarios(A);
            A=Dao.select("Codigo_Producto,Nombre_Producto,Precio_costo,Precio_venta","Productos",null);
                Market.createProductos(A);
            A=Dao.select("Nombre,RUC", "Distribuidores", null);
                Market.createDistribuidores(A);               
            A=Dao.select("Nombre_Persona,DNI,Telefono_Persona,Direccion_Persona", "Clientes,Persona", "idPersona,idPersona", null);
                Market.createClientes(A);
           
        //Crear Formularios
                
                frms.add(new frmLogin());
                frms.get(0).show();frms.get(0).requestFocusInWindow();
                frms.add(new frmListaProductos());
                frms.add(new frmListaDistribuidores());
                frms.add(new frmListaClientes());
                frms.add(new frmVerOperaciones());
                frms.add(new frmNuevaVenta());
         
        //objeto timer para evaluación constante de cambios en el sistema
        TimerTask task=new TimerTask(){
                        public void run(){
                            if(frmSolaris._ingresar)
                                frmSolaris.this.enable(true);
                        }
                    };
        Timer timer=new Timer();
        timer.scheduleAtFixedRate(task, 0, 100);
        
    }    
    /*Entrar al programa*/
    public static void ingresar(boolean entrar){
        frmSolaris._ingresar=entrar;
        //ocultar el login
        if(entrar)
           frmSolaris.frms.get(0).hide();       
        else
            JOptionPane.showMessageDialog(null, "Datos ingresados incorrectos.");
    }
    /**
     * Creates new form frmSolaris
     */
    public frmSolaris() {
        initComponents();
        frmSolaris.this.setLocationRelativeTo(null);
        frmSolaris.this.init();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mUsuario = new javax.swing.JMenu();
        mUsuarioConfigurar = new javax.swing.JMenu();
        mUsuarioSalir = new javax.swing.JMenu();
        mProductos = new javax.swing.JMenu();
        mProductosListaProductos = new javax.swing.JMenu();
        mDistribuidores = new javax.swing.JMenu();
        mDistribuidoresListaDistribuidores = new javax.swing.JMenu();
        mClientes = new javax.swing.JMenu();
        mClientesListaClientes = new javax.swing.JMenu();
        mOperaciones = new javax.swing.JMenu();
        mOperacionesVerOperaciones = new javax.swing.JMenu();
        mOperacionesNuevaVenta = new javax.swing.JMenu();
        mInfoSoporte = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        mInfoAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Solaris");
        setBackground(new java.awt.Color(255, 255, 255));
        setEnabled(false);
        setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N

        jMenuBar1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        mUsuario.setText("Usuario");

        mUsuarioConfigurar.setText("Confirgurar");
        mUsuario.add(mUsuarioConfigurar);

        mUsuarioSalir.setText("Salir");
        mUsuario.add(mUsuarioSalir);

        jMenuBar1.add(mUsuario);

        mProductos.setText("Productos");

        mProductosListaProductos.setText("Lista de Productos");
        mProductosListaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mProductosListaProductosMouseClicked(evt);
            }
        });
        mProductos.add(mProductosListaProductos);

        jMenuBar1.add(mProductos);

        mDistribuidores.setText("Distribuidores");

        mDistribuidoresListaDistribuidores.setText("Lista de Distribuidores");
        mDistribuidoresListaDistribuidores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mDistribuidoresListaDistribuidoresMouseClicked(evt);
            }
        });
        mDistribuidores.add(mDistribuidoresListaDistribuidores);

        jMenuBar1.add(mDistribuidores);

        mClientes.setText("Clientes");

        mClientesListaClientes.setText("Lista de clientes");
        mClientesListaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mClientesListaClientesMouseClicked(evt);
            }
        });
        mClientes.add(mClientesListaClientes);

        jMenuBar1.add(mClientes);

        mOperaciones.setText("Operaciones");

        mOperacionesVerOperaciones.setText("Ver Operaciones");
        mOperacionesVerOperaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mOperacionesVerOperacionesMouseClicked(evt);
            }
        });
        mOperaciones.add(mOperacionesVerOperaciones);

        mOperacionesNuevaVenta.setText("Nueva venta");
        mOperacionesNuevaVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mOperacionesNuevaVentaMouseClicked(evt);
            }
        });
        mOperaciones.add(mOperacionesNuevaVenta);

        jMenuBar1.add(mOperaciones);

        mInfoSoporte.setText("Información");

        jMenu1.setText("Soporte Técnico");
        mInfoSoporte.add(jMenu1);

        mInfoAyuda.setText("Ayuda");
        mInfoSoporte.add(mInfoAyuda);

        jMenuBar1.add(mInfoSoporte);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //entrar al formulario de productos
    private void mProductosListaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mProductosListaProductosMouseClicked
        frms.get(1).show();
            System.out.println("-------------");
        for(Producto p: Market.getProductos())
            System.out.println(p);
    }//GEN-LAST:event_mProductosListaProductosMouseClicked
    //entrar al formulario de la Lista de Distribuidores
    private void mDistribuidoresListaDistribuidoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mDistribuidoresListaDistribuidoresMouseClicked
        frms.get(2).show();
    }//GEN-LAST:event_mDistribuidoresListaDistribuidoresMouseClicked
    //entrar al formulario de la lista de Clientes
    private void mClientesListaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mClientesListaClientesMouseClicked
        frms.get(3).show();
    }//GEN-LAST:event_mClientesListaClientesMouseClicked
    //entrar a ver todas las operaciones que se han realizado en la lista de Operaciones
    private void mOperacionesVerOperacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mOperacionesVerOperacionesMouseClicked
        frms.get(4).show();
    }//GEN-LAST:event_mOperacionesVerOperacionesMouseClicked
    //entrar a realizar una nueva venta por parte del empleado
    private void mOperacionesNuevaVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mOperacionesNuevaVentaMouseClicked
        frms.get(5).show();
    }//GEN-LAST:event_mOperacionesNuevaVentaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSolaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSolaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSolaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSolaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSolaris().setVisible(true);
                
                
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mClientes;
    private javax.swing.JMenu mClientesListaClientes;
    private javax.swing.JMenu mDistribuidores;
    private javax.swing.JMenu mDistribuidoresListaDistribuidores;
    private javax.swing.JMenu mInfoAyuda;
    private javax.swing.JMenu mInfoSoporte;
    private javax.swing.JMenu mOperaciones;
    private javax.swing.JMenu mOperacionesNuevaVenta;
    private javax.swing.JMenu mOperacionesVerOperaciones;
    private javax.swing.JMenu mProductos;
    private javax.swing.JMenu mProductosListaProductos;
    private javax.swing.JMenu mUsuario;
    private javax.swing.JMenu mUsuarioConfigurar;
    private javax.swing.JMenu mUsuarioSalir;
    // End of variables declaration//GEN-END:variables
}
